### ISSUE TITLE
Create program diagram

### ISSUE THREAD

**Issue by SpongeBoyMeBahb** [monty1289/Pro-Prc-Group-Project#4]
Collaboration session using tools on miro to create program diagram
https://miro.com/welcomeonboard/SgunulAv3fWn5Opb2xcW1i2iTrZcb9dDQmtCUGVThQL9sUCYRFNGUUpFqb3o9Hcp

**Comment by SpongeBoyMeBahb** [comment]
We have created a basic diagram but it will need changes after we discuss which methods we need to make

**Comment by SpongeBoyMeBahb** [comment]
I have tweaked and completed the diagrams, needs approval from team. 
https://miro.com/app/board/o9J_ksCSGEU=/

**Comment by 37warmdog** [comment]
Draft plan looks good, moving forward with code
